<?php

require_once dirname(__FILE__) . '/../restiny.php';

/**
 * Test class for Restiny.
 * Generated by PHPUnit on 2011-05-04 at 04:05:18.
 */
class RestinyTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Restiny
	 */
	protected $object;

	protected function setUp() {
		$this->object = new Restiny;
	}

	protected function tearDown() {

	}


}

?>
