<?php

require_once dirname(__FILE__) . '/../../core/Config.php';

/**
 * Test class for Config.
 * Generated by PHPUnit on 2011-05-04 at 04:05:20.
 */
class ConfigTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Config
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Config;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testLoadConfig().
	 */
	public function testLoadConfig() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
