<?php

require_once dirname(__FILE__) . '/../../core/CycleManager.php';

/**
 * Test class for CycleManager.
 * Generated by PHPUnit on 2011-05-04 at 04:05:22.
 */
class CycleManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var CycleManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new CycleManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testRun().
	 */
	public function testRun() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
