<?php

require_once(dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'testBootstrap.php');
require_once dirname(__FILE__) . '/../../core/Request.php';

/**
 * Test class for Request.
 * Generated by PHPUnit on 2011-05-04 at 04:04:52.
 */
class RequestTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Request
	 */
	protected $object;

	protected function setUp() {

	}

	protected function tearDown() {

	}

	public function testRequestConstructException() {
		$_SERVER['REQUEST_METHOD'] = 'getc';
		$_SERVER['REQUEST_URI'] = '/feed/';

		$this->setExpectedException('RestinyHttpException', 'Request method is not allowed');

		$request = new Request();
	}

	public function testRequestConstruct() {
		$_SERVER['REQUEST_METHOD'] = 'get';
		$_SERVER['REQUEST_URI'] = '/feed/myFeed.json';

		$_GET = array(
			'uid' => '1000000001',
			'uname' => 'zhangyy'
		);

		$request = new Request();

		$this->assertEquals('GET', $request->getRequestMethod());
		$this->assertEquals('/feed/myFeed.json', $request->getRequestUri());
		$this->assertEquals('json', $request->getRequesetAccept());


		$this->assertEquals($_GET, $request->getRequestParams());
	}

}

?>
