<?php

require_once dirname(__FILE__) . '/../../core/Resource.php';

/**
 * Test class for Resource.
 * Generated by PHPUnit on 2011-05-04 at 04:05:25.
 */
class ResourceTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Resource
	 */
	protected $object;

	protected function setUp() {
		$this->object = new Resource;
	}

	protected function tearDown() {

	}

}

?>
