<?php

require_once dirname(__FILE__) . '/../../core/ResourceRouter.php';

/**
 * Test class for ResourceRouter.
 * Generated by PHPUnit on 2011-05-04 at 04:05:27.
 */
class ResourceRouterTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ResourceRouter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ResourceRouter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testLoadResource().
	 */
	public function testLoadResource() {
		$resquest = new Request();
		$resquest = new Response();

		$resource = ResourceRouter::loadResource($request, $response);
//		$exceptedResource =
//		$this->assertEquals($expected, $actual)
	}

}

?>
