<?php

require_once dirname(__FILE__) . '/../../core/Response.php';

/**
 * Test class for Response.
 * Generated by PHPUnit on 2011-05-04 at 04:05:24.
 */
class ResponseTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Response
	 */
	protected $object;

	protected function setUp() {
		$this->object = new Response;
	}

	protected function tearDown() {

	}
}

?>
