<?php

require_once dirname(__FILE__) . '/../../../core/Exception/RestinyException.php';

/**
 * Test class for RestinyException.
 * Generated by PHPUnit on 2011-05-04 at 04:05:35.
 */
class RestinyExceptionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var RestinyException
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new RestinyException;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

}

?>
