<?php

require_once dirname(__FILE__) . '/../../../core/Representor/Representor.php';

/**
 * Test class for Representor.
 * Generated by PHPUnit on 2011-05-04 at 04:05:43.
 */
class RepresentorTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Representor
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Representor;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

}

?>
